# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dfc26096d824d8f5aedb905ec08ae066f5d5a6a4880649fa032c7940783d7efc41d3c297345dc6cb37a590280de484c60c8ba3556c8c72c184ed8688ef94d692

test:
  secret_key_base: 211032f4d4d32292118a74e391b9b0a31cd3a2d3981b12d72be510dbb6167a3c83b668b0ef15eeb7dec6fe0bcdc8a05738deee6920076027aa9afc56f11e9ca9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
