# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9bb615f33055d203a97a4d3c8eb8ce19cfe76bb7a60009294c97016ffe5a79eca9d10dc764f97d52f5697075d10aab4a1b241e946e6d2d64da85d5fcfa9d3ce8

test:
  secret_key_base: 117e93d3a1f4df46b2bf123f82feb5156f80049955960b4da2888635376e621853952c2b900a103f022428513185d4149e6cd879aadf911123a007f627e9aac0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
